#! /bin/zsh
if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ];then
  echo "To use this script run $0 <server name> <IP to add> <ASN>"
  echo "Where <server name> is the name of a file in /evix/scripts/remote-scripts/hosts"
  echo "and <ASN> is the ASN of the user (for updating the tunnels table in the database)"
  echo
  echo "On a sucessful run, the tunnel ID will be returned"
  exit
fi

cd /evix/scripts/remote-scripts
./runRemoteScript scripts/eoip-add $1 $2

/usr/bin/php /evix/scripts/add-remote-ip.php $3 $2 "eoip"
