#! /bin/zsh
if [ -z "$1" ];then
  echo "To use this script run $0 <ASN>"
  echo "Where <ASN> is the name of the ASN that you want to find the details for"
  echo
  echo "On a sucessful run, some details about open peering requests from this ASN will be returned"
  exit
fi

echo "Found these pending peers:"
/evix/scripts/approve_peer.sh pending | grep -A 5 "ASN: $1" | awk '{print "    " $0}'
echo
echo "Found these peers of any status:"
/evix/scripts/remote-scripts/scripts/all-peers.sh pending | grep -A 6 "ASN: $1" | awk '{print "    " $0}'
