#! /bin/zsh
if [ -z "$1" ] || [ -z "$2" ];then
  echo "To use this script run $0 <ASN> <ZT address> <IPs to add>"
  echo "Where <server name> is the name of a file in /evix/scripts/remote-scripts/hosts"
  echo "and <ASN> is the ASN of the user (for updating the tunnels table in the database)"
  echo "and <ZT address> is the ZeroTier address of th euser"
  echo
  echo "On a sucessful run, the tunnel ID will be returned"
  exit
fi

asn=$1
shift

cd /evix/scripts/remote-scripts
./runRemoteScript scripts/zerotier-add zt-root0 $@

/usr/bin/php /evix/scripts/add-remote-ip.php $asn $1 "vxlan"
