#! /bin/zsh
cd /evix/eoip
echo
echo "New tunnel:"
cut -d \" \" -f 1 < peers.eoip | #reads from the peers file and gets all the IDs
sort -n | #sorts the IDs in case they aree not already
awk '{ do{ for(s=e="'$1'"; (r=getline)>0 && "'$1'"<=e+1; e="'$1'"); print s==e ? s : s\",\"e }while(r>0) }' | #this makes no sense to me, see https://unix.stackexchange.com/questions/470073/how-to-collapse-consecutive-numbers-into-ranges
head -n 1 | #get just the first range
cut -d \",\" -f 2 | #find the end of the range
xargs -I id expr id + 1 | #add one to get the next avalible ID
xargs -I id echo id $1 | #format the new IP
tee -a peers.eoip #add it to the file
sort -n peers.eoip -o peers.eoip #make sure the file is sorted
echo
echo "New tunnel listing:"
cat peers.eoip
echo
echo "'"Your new tunnel ID is $(grep '"$1"' /evix/eoip/peers.eoip | cut -d '"' '"' -f 1)"'"
echo "'"Our endpoint is: $(head -n 3 eoip.sh | tail -n 1 | rev | cut -d '"' '"' -f1 | rev)"'"
/evix/eoip/eoip.sh 2&>/dev/null
