#! /bin/bash

cd json || exit

jq -L/evix/scripts -r '{roots: .zt.roots, key: .zt.world_secret} | zt_create_world("moon")' /evix/secret-config.json > moon.json
jq -L/evix/scripts -r '{roots: .zt.roots, key: .zt.world_secret} | zt_create_world("planet")' /evix/secret-config.json > planet.json

cd ../
zerotier-idtool genmoon json/moon.json
zerotier-idtool genmoon json/planet.json

mv 0000000227883110.moon planet

cp -u planet /evix/run/IX-Website/files/
cp -u 0000002cb385e495.moon /evix/run/IX-Website/files/

#alt_id="~/.ssh/id_rsa"

#if (( EUID != 0 )); then
#  if [ ! -f ~/.ssh/alt/id_rsa ]; then
#    echo "It appears you may not have access to the tunnel servers?"
#    exit -1
#  fi
#  alt_id="~/.ssh/alt/id_rsa"
#fi

#scp -i $alt_id planet root@23.129.32.56:/var/lib/zerotier-one/
#scp -i $alt_id 0000002cb385e495.moon root@23.129.32.56:/var/lib/zerotier-one/moons.d/
#ssh root@23.129.32.56 killall zerotier-one
