- hosts: tunnelservers
  tasks:
    - name: Push config to tunnel servers
      synchronize:
        src: /evix/
        dest: /evix/
        checksum: yes
        delete: yes
        group: no
        owner: no
        rsync_opts:
          - "--exclude-from=/evix/.gitignore"
    - name: Push peers config to tunnel servers
      synchronize:
        src: /evix/config/peers/
        dest: /evix/config/peers/
        checksum: yes
        delete: yes
        group: no
        owner: no
    - name: Reconfigure tunnels
      command: /evix/scripts/ts/update.sh
