- hosts: tunnelservers
  tasks:
    - name: Push openvpn config to tunnel servers
      synchronize:
        src: /evix/config/openvpn/
        dest: /etc/openvpn/
        checksum: yes
        delete: no
        group: no
        owner: no
        dirs: yes
        recursive: no
      register: ovpn_config
    - name: Restart openvpn
      systemd:
        name: openvpn@server.service
        state: restarted
      when: ovpn_config.changed
    - name: Enable openvpn and ensure it is not masked
      systemd:
        name: openvpn@server.service
        enabled: yes
        masked: no