- hosts: routeservers-primary
  tasks:
    - name: Update bird config file
      template:
        src: /evix/config/bird/bird_fmt.conf
        dest: /etc/bird/bird.conf
      notify: reconfigure bird
    - name: Update bird6 config file
      template:
        src: /evix/config/bird/bird6_fmt.conf
        dest: /etc/bird/bird6.conf
      notify: reconfigure bird6
    - template:
        src: /etc/bird/header.local
        dest: /etc/bird/header.local
  handlers:
    - name: reconfigure bird
      command: /usr/sbin/birdc configure
    - name: reconfigure bird6
      command: /usr/sbin/birdc6 configure

- hosts: routeservers-secondary
  tasks:
    - name: Update bird config file
      template:
        src: /evix/config/bird/bird_ams.conf
        dest: /etc/bird/bird.conf
        mode: 0644
      notify: reconfigure bird
    - name: Update bird6 config file
      template:
        src: /evix/config/bird/bird6_ams.conf
        dest: /etc/bird/bird6.conf
        mode: 0644
      notify: reconfigure bird6
    - template:
        src: /etc/bird/header.local
        dest: /etc/bird/header.local
  handlers:
    - name: reconfigure bird
      command: /usr/sbin/birdc configure
    - name: reconfigure bird6
      command: /usr/sbin/birdc6 configure

